/**
 * Adeeb LMS — 6 color themes (Theme 1 = default :root / orange)
 * Each theme mirrors Adeeb Classic structure; only palette values differ.
 */
export const APP_THEMES = [
  {
    id: 'orange',
    number: 1,
    name: 'Adeeb Classic',
    tagline: 'Official Brand Identity',
    primary: '#ff8e01',
    primaryDark: '#e67e00',
    secondary: '#222d38',
    sidebar: '#222d38',
    sidebarLight: '#394251',
    sidebarDark: '#1a232c',
    bgMain: '#F8FAFC',
    bgCard: '#FFFFFF',
    textPrimary: '#1E293B',
    textSecondary: '#64748B',
    onPrimary: '#FFFFFF',
  },
  {
    id: 'gold',
    number: 2,
    name: 'Luxury Gold',
    tagline: 'Premium & Elegant',
    primary: '#f5d7a5',
    primaryDark: '#f5d7a5',
    secondary: '#6b3d25',
    sidebar: '#6b3d25',
    sidebarLight: '#8b5a3a',
    sidebarDark: '#4a2a1a',
    bgMain: '#F8FAFC',
    bgCard: '#FFFFFF',
    textPrimary: '#65371d',
    textSecondary: '#8b6348',
    onPrimary: '#65371d',
  },
  {
    id: 'olive',
    number: 3,
    name: 'Olive Garden',
    tagline: 'Nature & Harmony',
    primary: '#678018',
    primaryDark: '#678018',
    secondary: '#324321',
    sidebar: '#324321',
    sidebarLight: '#4a5f30',
    sidebarDark: '#253218',
    bgMain: '#F8FAFC',
    bgCard: '#FFFFFF',
    textPrimary: '#2f401e',
    textSecondary: '#5a6b42',
    onPrimary: '#FFFFFF',
  },
  {
    id: 'navy',
    number: 4,
    name: 'Blue Harmony',
    tagline: 'Teal, Royal & Deep Blue',
    primary: '#2D58B7',
    primaryDark: '#152E5C',
    secondary: '#152E5C',
    sidebar: '#152E5C',
    sidebarLight: '#1477A1',
    sidebarDark: '#152E5C',
    bgMain: '#F8FAFC',
    bgCard: '#FFFFFF',
    textPrimary: '#152E5C',
    textSecondary: '#5a7199',
    onPrimary: '#FFFFFF',
  },
  {
    id: 'lavender',
    number: 5,
    name: 'Royal Lavender',
    tagline: 'Creative & Calm',
    primary: '#fedef6',
    primaryDark: '#fedef6',
    secondary: '#6841c2',
    sidebar: '#6841c2',
    sidebarLight: '#9b84ec',
    sidebarDark: '#4e3192',
    bgMain: '#F8FAFC',
    bgCard: '#FFFFFF',
    textPrimary: '#4e2bab',
    textSecondary: '#9b84ec',
    onPrimary: '#4e2bab',
  },
  {
    id: 'rose-pink',
    number: 6,
    name: 'Rose Petal',
    tagline: 'Bold & Passionate',
    primary: '#f83c93',
    primaryDark: '#f83c93',
    secondary: '#b11954',
    sidebar: '#b11954',
    sidebarLight: '#d42d6e',
    sidebarDark: '#8c1442',
    bgMain: '#F8FAFC',
    bgCard: '#FFFFFF',
    textPrimary: '#920d3e',
    textSecondary: '#c42d65',
    onPrimary: '#FFFFFF',
  },
  {
    id: 'pakistan-green',
    number: 7,
    name: 'Pakistan Green',
    tagline: 'Green & White Pride',
    primary: '#02BF57',
    primaryDark: '#01411C',
    secondary: '#FFFFFF',
    sidebar: '#01411C',
    sidebarLight: '#02BF57',
    sidebarDark: '#002B13',
    bgMain: '#FFFFFF',
    bgCard: '#FFFFFF',
    textPrimary: '#01411C',
    textSecondary: '#4B6355',
    onPrimary: '#FFFFFF',
    swatches: ['#1477A1', '#2D58B7', '#152E5C'],
    swatches: ['#FFFFFF', '#01411C', '#02BF57'],
  },
];

export const getThemeById = (id) => APP_THEMES.find((t) => t.id === id) || APP_THEMES[0];
